// The cart region and the relocation pass that makes its pointers mean
// something here.

#ifndef AGB_CART_H
#define AGB_CART_H

#include <stdint.h>

// One pointer in the ROM whose target is a symbol rather than more ROM data:
// a function to call, or a RAM variable to reach. `target` is filled in by our
// own linker, so nothing looks symbols up at run time.
struct agb_reloc_symbol
{
    uint32_t offset;      // where in the cart image the pointer sits
    const void *target;   // what it should point at here
    int32_t addend;       // how far past the symbol it pointed there
};

// Generated by tools/gen_relocations.py.
extern const uint32_t agb_reloc_data[];
extern const uint32_t agb_reloc_data_count;
extern const struct agb_reloc_symbol agb_reloc_symbols[];
extern const uint32_t agb_reloc_symbol_count;

// Load a ROM image into the cart region and rewrite the pointers inside it.
// Returns 0 on success, or a negative errno-style code: the file could not be
// read, or it is not the size the region expects.
int agb_cart_load(const char *path);

// The pass on its own, over an image already in the cart region. Separated so a
// test can drive it without a file.
void agb_cart_relocate(void);

#endif
