#include <stdio.h>
#include <stdlib.h>

// Link-time target for game code the port has not implemented yet. Reaching one
// is a bug report, not a crash: it names the routine so the gap is identifiable.
// The stub bodies are generated by tools/gen_symbol_bindings.py.
void agb_unimplemented_named(const char *name)
{
    fprintf(stderr, "\nagb: unimplemented routine: %s\n", name);
    fprintf(stderr, "agb: see docs/ROADMAP.md for which phase implements it\n");
    abort();
}

void agb_unimplemented(void)
{
    agb_unimplemented_named("<unnamed>");
}

// Subsystems a later phase owns: sound, link, multiboot. Warned once each so a
// run reports exactly what it did without them, then continues.
#define AGB_DEFERRED_REPORT_MAX 64

static const char *agb_reported[AGB_DEFERRED_REPORT_MAX];
static int agb_reported_count;

int agb_deferred_named(const char *name)
{
    for (int i = 0; i < agb_reported_count; i++)
    {
        if (agb_reported[i] == name)
            return 0;
    }

    if (agb_reported_count < AGB_DEFERRED_REPORT_MAX)
    {
        agb_reported[agb_reported_count++] = name;
        fprintf(stderr, "agb: deferred subsystem call: %s\n", name);
    }
    return 0;
}
