#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Link-time targets for game code the port has not implemented yet. Reaching
// one is a bug report, not a crash: it names the routine so the gap is
// identifiable. The stub bodies are generated by tools/gen_symbol_bindings.py.
//
// These run inside the V-blank signal handler, so reporting uses write() rather
// than stdio: a handler that took the stdio lock while the interrupted context
// already held it would deadlock.

static void emit(const char *prefix, const char *name)
{
    char buf[160];
    size_t n = 0;
    size_t plen = strlen(prefix);
    size_t nlen = strlen(name);

    if (plen + nlen + 2 > sizeof(buf))
        nlen = sizeof(buf) - plen - 2;

    memcpy(buf, prefix, plen);
    n += plen;
    memcpy(buf + n, name, nlen);
    n += nlen;
    buf[n++] = '\n';

    ssize_t ignored = write(2, buf, n);
    (void)ignored;
}

void agb_unimplemented_named(const char *name)
{
    emit("\nagb: unimplemented routine: ", name);
    emit("agb: see docs/ROADMAP.md for the phase that implements ", name);
    abort();
}

void agb_unimplemented(void)
{
    agb_unimplemented_named("<unnamed>");
}

// Subsystems a later phase owns: sound, link, flash, multiboot. Warned once
// each, so a run reports exactly what it did without them, then continues.
#define AGB_DEFERRED_REPORT_MAX 128

static const char *agb_reported[AGB_DEFERRED_REPORT_MAX];
static int agb_reported_count;

int agb_deferred_named(const char *name)
{
    for (int i = 0; i < agb_reported_count; i++)
    {
        if (agb_reported[i] == name)
            return 0;
    }

    if (agb_reported_count < AGB_DEFERRED_REPORT_MAX)
    {
        agb_reported[agb_reported_count++] = name;
        emit("agb: deferred subsystem call: ", name);
    }
    return 0;
}
