#!/usr/bin/env python3
"""Bind symbols the native build cannot define to the right place in the arena.

Three of the four categories are real bindings, not stubs: data that lives in the
ROM is bound into the cart region, and EWRAM/IWRAM variables are bound to their
true offsets in the memory arena. Only code the port has not implemented yet
becomes a stub, and that stub aborts loudly rather than misbehaving quietly.

Emits a linker response file. Use --driver when feeding it to a compiler driver,
which expands @files itself and does not understand --defsym.
"""
import argparse
import sys

CART_BASE = 0x08000000
EWRAM_BASE = 0x02000000
IWRAM_BASE = 0x03000000

# Offsets of each region within `struct agb_memory`; see platform/agb/include/agb/memmap.h
EWRAM_OFF = 0x0
IWRAM_OFF = 0x40000

EWRAM_SIZE = 0x40000
IWRAM_SIZE = 0x8000


def read_syms(path):
    """A .sym row is: addr binding size name"""
    out = {}
    with open(path) as fh:
        for line in fh:
            parts = line.split()
            if len(parts) != 4:
                continue
            try:
                addr = int(parts[0], 16)
            except ValueError:
                continue
            out.setdefault(parts[3], addr)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("symfile")
    ap.add_argument("wanted", help="newline-separated symbols to bind")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--text-end", required=True, help="end of .text, hex")
    ap.add_argument("--driver", action="store_true")
    ap.add_argument("--stub-source",
                    help="write one named stub per unimplemented routine here")
    # Subsystems a phase defers wholesale. Their stubs warn once and return
    # instead of aborting, so the frame loop can run without them. Everything
    # else stays a hard stop -- a silent no-op in game logic is far worse than
    # a crash, because it looks like it worked.
    ap.add_argument("--soft-prefix", action="append", default=[],
                    help="routines starting with this warn and return")
    ap.add_argument("--soft-list",
                    help="file of exact symbol names to treat as deferred")
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    text_end = int(args.text_end, 16)
    syms = read_syms(args.symfile)
    with open(args.wanted) as fh:
        wanted = [w.strip() for w in fh if w.strip()]

    lines, tally, unknown = [], {"cart": 0, "ewram": 0, "iwram": 0, "stub": 0}, []
    stubs = []

    for name in wanted:
        addr = syms.get(name)
        if addr is None:
            unknown.append(name)
            continue
        if EWRAM_BASE <= addr < EWRAM_BASE + EWRAM_SIZE:
            target = f"agb_mem+0x{EWRAM_OFF + addr - EWRAM_BASE:X}"
            tally["ewram"] += 1
        elif IWRAM_BASE <= addr < IWRAM_BASE + IWRAM_SIZE:
            target = f"agb_mem+0x{IWRAM_OFF + addr - IWRAM_BASE:X}"
            tally["iwram"] += 1
        elif CART_BASE <= addr < text_end:
            # A named stub per routine, so a diagnostic says which one was hit
            # rather than pointing every gap at one shared address.
            stubs.append(name)
            tally["stub"] += 1
            continue
        elif addr >= text_end:
            target = f"agb_cart+0x{addr - CART_BASE:X}"
            tally["cart"] += 1
        else:
            unknown.append(name)
            continue
        lines.append((name, target))

    with open(args.output, "w") as fh:
        for name, target in lines:
            if args.driver:
                fh.write(f"-Wl,--defsym,{name}={target}\n")
            else:
                fh.write(f"--defsym {name}={target}\n")

    soft_names = set()
    if args.soft_list:
        with open(args.soft_list) as fh:
            soft_names = {line.strip() for line in fh if line.strip()}

    if args.stub_source:
        soft = [s for s in stubs
                if s in soft_names or any(s.startswith(p) for p in args.soft_prefix)]
        hard = [s for s in stubs if s not in set(soft)]
        with open(args.stub_source, "w") as fh:
            fh.write("// Generated by tools/gen_symbol_bindings.py. Do not edit.\n")
            fh.write("// One stub per routine the port has not implemented yet.\n\n")
            fh.write("void agb_unimplemented_named(const char *name);\n")
            fh.write("int agb_deferred_named(const char *name);\n\n")
            for name in hard:
                fh.write(f"void {name}(void) {{ agb_unimplemented_named(\"{name}\"); }}\n")
            fh.write("\n")
            for name in soft:
                fh.write(f"int {name}(void) {{ return agb_deferred_named(\"{name}\"); }}\n")
        tally["stub"] = len(hard)
        tally["deferred"] = len(soft)

    if args.report:
        print(f"bound {len(lines)} symbols", file=sys.stderr)
        for k in ("cart", "ewram", "iwram", "stub", "deferred"):
            if k in tally:
                print(f"  {k:8} {tally[k]:5d}", file=sys.stderr)
        if unknown:
            print(f"  unknown {len(unknown)}: {', '.join(unknown[:8])}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
